CREATE TABLE documents
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type         VARCHAR(255)                            NOT NULL,
    organization VARCHAR(128)                            NOT NULL,
    description  VARCHAR(512)                            NOT NULL,
    patient      VARCHAR(128)                            NOT NULL,
    date         DATE                                    NOT NULL,
    status       VARCHAR(16)                             NOT NULL,
    CONSTRAINT pk_documents PRIMARY KEY (id)
);