CREATE TABLE documents
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type         VARCHAR(255) NOT NULL,
    organization VARCHAR(128) NOT NULL,
    description  VARCHAR(512) NOT NULL,
    patient      VARCHAR(128) NOT NULL,
    date         DATE         NOT NULL,
    status       VARCHAR(16)  NOT NULL,
    CONSTRAINT pk_documents PRIMARY KEY (id)
);

CREATE TABLE outbox
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    payload text NOT NULL,
    CONSTRAINT pk_outbox PRIMARY KEY (id)
);

CREATE TABLE inbox
(
    id      BIGINT,
    payload bytea   NOT NULL,
    is_read BOOLEAN NOT NULL,
    CONSTRAINT pk_inbox PRIMARY KEY (id)
);