FROM nginx:1.19.7
COPY dist/main.js /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY public/index.html /usr/share/nginx/html/index.html
COPY public/css /usr/share/nginx/html/css

